This is makeindex, version 2.16 [MiKTeX 24.1].
Scanning style file ./Math-Basics.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file Math-Basics.acn....done (4 entries accepted, 0 rejected).
Sorting entries....done (9 comparisons).
Generating output file Math-Basics.acr....done (14 lines written, 0 warnings).
Output written in Math-Basics.acr.
Transcript written in Math-Basics.alg.
